// React + Vite/react_vite_wordle/src/components/GameGrid.jsx
import React from 'react';
import WordleInput from './WordleInput';

const GameGrid = ({ word, guesses, onGuessSubmit }) => {
    const rows = 6;
    const cols = 5;

    const renderCell = (rowIndex, colIndex) => {
        const guess = guesses[rowIndex];
        
        if (guess && guess.word[colIndex]) {
            const letter = guess.word[colIndex];
            const evaluation = guess.evaluation[colIndex];
            return (
                <div className={`cell ${evaluation}`} key={`${rowIndex}-${colIndex}`}>
                    {letter}
                </div>
            );
        }
        
        return (
            <div className="cell" key={`${rowIndex}-${colIndex}`}></div>
        );
    };

    const renderGrid = () => {
        const cells = [];
        for (let row = 0; row < rows; row++) {
            for (let col = 0; col < cols; col++) {
                cells.push(renderCell(row, col));
            }
        }
        return cells;
    };

    return (
        <div className="grid" id="grid">
            {renderGrid()}
            <WordleInput word={word} guesses={guesses} onGuessSubmit={onGuessSubmit} />
        </div>
    );
};

export default GameGrid;

// Svelte/src/lib/components/GameGrid.svelte
<script>
    import WordleInput from './WordleInput.svelte';
    
    let { word, guesses, onGuessSubmit, hasWon, hasLost } = $props();

    const rows = 6;
    const cols = 5;
</script>

<div class="grid" id="grid">
    {#each Array(rows) as _, rowIndex}
        {#each Array(cols) as _, colIndex}
            {@const guess = guesses[rowIndex]}
            {#if guess && guess.word[colIndex]}
                {@const letter = guess.word[colIndex]}
                {@const evaluation = guess.evaluation[colIndex]}
                <div class="cell {evaluation}">{letter}</div>
            {:else}
                <div class="cell"></div>
            {/if}
        {/each}
    {/each}
    <WordleInput {word} {guesses} {onGuessSubmit} {hasWon} {hasLost} />
</div>
